import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/common";

const archivo = Archivo({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
  title: "Apex Mechanic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
